apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:   
      containers:
      - name: httpd
        image: httpd
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
