apiVersion: v1
kind: Service
metadata: 
  name: myapp-svc
spec:
  type: NodePort
  ports:
  -  port: 8080
     targetPort: 80
     nodePort: 30000
  selector:
    role: myapp



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
spec:
  replicas: 2
  selector:
    matchLabels:
        role: myapp
  template:
    metadata:
      labels:
        role: myapp
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        -  name: myapp-html-volume
           mountPath: /usr/local/apache2/htdocs/
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
        - name: myapp-html-volume
          configMap:
            name: apache-html
            items:
            - key: "index.html"
              path: "index.html"
            - key: "index.css"
              path: "index.css"
            - key: "index.js"
              path: "index.js"
            - key: "hero.jpg"
              path: "hero.jpg"
            - key: "profile-img-def.jpg"
              path: "profile-img-def.jpg"

  

