apiVersion: v1
kind: Service
metadata: 
  name: http-test-svc
spec:
  type: NodePort
  ports:
  -  port: 8080
     targetPort: 80
     nodePort: 30000
  selector:
    role: test



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-test-dply
spec:
  selector:
    matchLabels:
      role: test
  replicas: 2
  template:
    metadata:
      labels:
        role: test
    spec:   
      containers:
      - name: http-test
        image: httpd
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
